#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ -n "$2" ]]; then
  grep " $2" "$SCRIPT_DIR"/"$1" | awk -F ' ' '{print $1}'
else
  grep -h "^$1" "$SCRIPT_DIR"/* --exclude=tw --exclude=README.md | head -n 1
fi
